### ISSUE TITLE
broken links to SemOpenAlex authors

### ISSUE THREAD

**Issue by VladimirAlexiev** [davidlamprecht/linkedpaperswithcode#5]
@davidlamprecht 
```
curl -L -Haccept:text/turtle https://linkedpaperswithcode.com/paper/on-the-use-of-arxiv-as-a-dataset
  owl:sameAs                   ns4:W2943043881
  dcterms:creator              ns7:A2033371752 , ns7:A2157679762 , ns7:A2143774550 , ns7:A2641167929
```
But these author links are broken (I looked at the first two).

cc @linnaung, @phaasenase:
Looking in SemOpenAlex we find the true author IDs:
```
curl -L -Haccept:text/turtle https://semopenalex.org/work/W2943043881
  dct:creator <https://semopenalex.org/author/A5035136886>, <https://semopenalex.org/author/A5036325834>,
    <https://semopenalex.org/author/A5035741296>, <https://semopenalex.org/author/A5007389688>;
```

**Comment by davidlamprecht** [comment]
This is because OpenAlex released a completely redesigned and improved author disambiguation in July 2023. As a result of this change, the old OpenAlex author IDs were deprecated and new author IDs were assigned to all authors (see: https://docs.openalex.org/api-entities/authors/author-disambiguation).

These outdated links to SemOpenAlex authors are only included in the first LPWC version v1. The new LPWC version v2 contains the up-to-date links to SemOpenAlex authors.

**Comment by davidlamprecht** [comment]
We have published the new LPWC version v2, which is based on the Papers with code dump from 19.12.2023, on zenodo today (see: https://zenodo.org/records/10479729). The new version is also already loaded into the public SPARQL endpoint.

**Comment by davidlamprecht** [comment]
The new LPWC version v2 is now accessible via the SPARQL endpoint and curl. E.g. See the correct links to SemOpenAlex authors for your example:

```
curl -L -Haccept:text/turtle https://linkedpaperswithcode.com/paper/on-the-use-of-arxiv-as-a-dataset
  owl:sameAs                   ns4:W2943043881 ;
  dcterms:creator              ns7:A5035741296 , ns7:A5007389688 , ns7:A5035136886 , ns7:A5036325834 ;
```
